[build]
target-dir = "target-nightly"

[target.'cfg(all(not(target_arch = "wasm32"), any(target_arch = "x86_64", target_arch = "aarch64")))']
rustflags = ["-C", "target-cpu=native"]

[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"
rustflags = ["-C", "target-feature=+simd128"]
